### ISSUE TITLE
Microfrontend parcel giving cors error

### ISSUE THREAD

**Issue by khurm786** [WJSoftware/vite-plugin-single-spa#14]
Hi, currently testing this library in a production environment.

Both the parcel and root are react/vite applications. 

When running both the root and parcel in dev everything works fine.
When building both the root and parcel locally and running it with `npm run preview` both the parcel and root are on localhost with different ports and everything works fine.

When in production the root and parcel are on different hostnames and are giving a cors error: 
`has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

I've tried the following: https://github.com/vitejs/vite/issues/12891 with:
`cors: false` but this didn't work.

Any ideas?

**Comment by webJose** [comment]
Hello!  CORS is not a function for this plug-in or for Vite when you deploy a built solution.  You see, once you build, Vite and this plug-in disappear from scene.  You are left with the `/dist` folder.  Question for you:  What do you do with the contents of `/dist`?  I suppose you put them in a location in a server somewhere to be served by an HTTP server.  What server do you use?  Normally at work, I use Kubernetes, so after building I put all of the contents of the `/dist` folder in a Linux image with Nginx.  Nginx is my web server after building and deploying.  What's yours?

Well, to resolve this, you must resolve it by configuring **your** production web server.  You must tell **your** web server of choice to allow the CORS call.

**Comment by khurm786** [comment]
Yes this was correct, I have the same setup as yours, allowing cors call in the nginx file fixed the issue.
