### ISSUE TITLE
Vue3 + Vite example ?

### ISSUE THREAD

**Issue by quentin-desbin** [WJSoftware/vite-plugin-single-spa#70]
## Is your feature request related to a problem?

[X] Root Config [X] Micro-frontend/parcel

## Describe the solution you'd like

Is it possible to have a little example with a small micro-frontend project and root project from vite and vue3?

## Describe alternatives you've considered

I tried to reproduce what you'd achieve with https://github.com/webJose/single-spa-and-svelte but with a vue3 project.
It works on dev mode (microfrontend as dev, and root as dev), but it doesn't works on preview. The components are loaded but the CSS is not displayed. I have no CSS files, only <style> and <style scoped> on my app-components

```javascript
// vite.config.mjs
export default defineConfig({
  plugins: [
    vue(),
    VueI18nPlugin({
      // locale messages resource pre-compile option
      include: resolve(dirname(fileURLToPath(import.meta.url)), './src/resources/locales/*.json'),
    }),
    vitePluginSingleSpa({
      type: 'mife',
      serverPort: 5173,
      spaEntryPoints: 'src/spa.js',
      cssStrategy: 'singleMife',
    })
  ],
  resolve: {
    alias: {
      '@': fileURLToPath(new URL('./src', import.meta.url))
    }
  },
  envDir: './env',
  base: '/spa1' // TODO : only for build
})
```

```javascript
// src/spa.js
import singleSpaVue from 'single-spa-vue'
import { cssLifecycleFactory } from 'vite-plugin-single-spa/ex'
import * as Vue from 'vue'
import { createApp } from 'vue'
import { createPinia } from 'pinia'

import i18n from '@/resources/locales/i18n'

import App from './App.vue'
import router from './router'

const lc = singleSpaVue({
    createApp,
    appOptions: {
        Vue,
        render() {
            return Vue.h(App)
        }
    },
    handleInstance: (app) => {
        const pinia = createPinia()

        app
        .use(router) // router
        .use(pinia) // pinia store module
        .use(i18n) // i18n module
        .component(...) // some global components
    }
})

const cssLc = cssLifecycleFactory('spa')
export const bootstrap = [cssLc.bootstrap, lc.bootstrap]
export const mount = [cssLc.mount, lc.mount]
export const unmount = [cssLc.unmount, lc.unmount]
```

On my root project I also use vite + vitePluginSingleSpa as 'root'. Here is my main.js:
```javascript
import { registerApplication, start } from "single-spa"

const spa = {
    "spa1": "my-app"
}

registerApplication(
    'spa1',
    () => import(/* @vite-ignore */ spa.spa1),
    location => location.pathname.startsWith('/spa1')
)

start()
```

I just want to achieve keeping my project with vite (avoid a webpack migration), but make it compatible with single-spa. Do you think it's possible ? I think a little example can unlock. Thanks :)

**Comment by quentin-desbin** [comment]
Yes, I used an import map named my-app (forgot to include on my previous comment), which links to : http://localhost:5173/spa.js

root is on 5174 and spa is on 5173

I will take time to perform a public repo and share the code, thanks!

**Comment by lencys** [comment]
A complete example of Vite + single-spa + web component would be very helpful to me. Otherwise, great job.

**Comment by webJose** [comment]
Hello, @lencys.  This GitHub has Discussions open, if you would like to start one.

As for web components, I don't do them, but if you would like to contribute with an example, it would be welcome.

Cheers.

**Comment by webJose** [comment]
Hello, @quentin-desbin.  Any updates?  If you can, let me know so I can close the issue.  Thanks!

**Comment by quentin-desbin** [comment]
I didn't get the time to re-test and create a public repo (it was tested on my enterprise repo), maybe you can close and when I will get time I can reopen with a link ;) ?

**Comment by ibjorn** [comment]
Apologies for rehashing this thread, but I have a very similar setup. Vue3 `root app` and Vue3 `mife`, both with Vite of course.

I managed to get the two working with some minor issues here and there related to CSS and especially routing when trying to navigate to a separate `mife` (it's as if the active `mife`'s router takes precedence. I might have workarounds for these, but have a bigger issue at hand while still testing whether this is a viable solution.

In my `root app`, I'm passing `customProps` in my main.ts file:

```
registerApplication({
    name: 'paymentGate',
    app: () => import(/* @vite-ignore */ paymentGateoModule),
    activeWhen: '/payment-gate/',
    customProps: {some: 'value'}
})
```

I can't quite figure out how to get those props in the `mife`. My `spa.ts` looks like this:

```
const lc = singleSpaVue({
    createApp,
    appOptions: {
        render() {
            return h(App, {
                props: {
                    name: 'paymentGate'
                    // mountParcel: this.mountParcel,
                    // singleSpa: this.singleSpa
                }
            })
        }
    },
    handleInstance: (app) => {
        registerPlugins(app)
        app.use(router)
    }
})
const cssLc = cssLifecycleFactory('spa')

console.log(lc)
export const bootstrap = [cssLc.bootstrap, lc.bootstrap]
export const mount = [cssLc.mount, lc.mount]
export const unmount = [cssLc.unmount, lc.unmount]
```

*the `mountParcel` and `singleSpa` keys don't seem to exist in `single-spa-vue` on `appOptions`.

I'm not 100% sure whether I even have the setup right due to the lack of documentation and examples.

I also can't figure out how to get to those `customProps` in the `mife`.

**Comment by webJose** [comment]
Hello, @ibjorn.  The TypeScript from the single-spa packages is not to be trusted.  If the comment says "uncomment to assign the props", you should do it.  By extension, I can only imagine that you can also do it for your custom props.

**Comment by ibjorn** [comment]
Hi @webJose, pardon my ignorance, but where is that comment you mention?

**Comment by webJose** [comment]
Interesting:  Don't remember.  Anyway:  The [Vue documentation](https://single-spa.js.org/docs/ecosystem-vue) states that properties coming from single-spa are available in the `this` object.  Have you examined the object to validate this claim?

**Comment by ibjorn** [comment]
When I log `this`, I see my custom prop there, along with `singleSpa` and `mountParcel`. However, as mentioned above, TypeScript complains bitterly about where I am trying to add it as `props`, as per my comment above.

Do you perhaps have any tips on how I could get it from there into my app?

Would it be wise to push it to a store inside spa.ts? Seems like something that should be handled in App.vue rather? Sorry, I know I'm digressing from the subject, I just can't find any info on this for Vue. Tons for React, nothing for Vue.

**Comment by webJose** [comment]
Typescript is just type checking.  The single-spa packages are notoriously bad in the TypeScript arena.  My recommendation is:  Examine the objects, follow the instructions and give TypeScript, in this particular case, the least priority.  In other words:  If I were you, I'd just add as the example states, and ignore TS errors with `// @ts-ignore` or `// @ts-expect-error`.

**Comment by ibjorn** [comment]
I have to admit, it feels to me like single-spa isn't really ready for Vue.

**Comment by quentin-desbin** [comment]
@ibjorn not sure that can help you because we are not using but we are using single-spa with customProps and it's working like a charm

root app:
```javascript
registerApplication(
    "name",
    // eslint-disable-next-line no-undef
    () => System.import("name"),
    (location) => location.pathname.startsWith("/"),
    { myProp: "example" }
)
```

On the spa/mife:
```javascript
singleSpaVue({
    createApp,
    appOptions: {
        render() {
            console.log(this.myProp) // will return "example"
            return h(App)
        }
    },
)}
```

Maybe it can helps you ;)

And to make this prop available in whole app, we exposed it in `window` (not the best, but the easiest in our case)

**Comment by ibjorn** [comment]
Hi @quentin-desbin, thanks for the reply. That is more or less what I currently have. I see what you're doing differently there under `appOptions`.

I'm just a bit stumped as to how I can securely get those props into my app.

**Comment by ibjorn** [comment]
So this is the interesting thing. I can see my props, and they're in `<App />`. But how does one access them?

![image](https://github.com/WJSoftware/vite-plugin-single-spa/assets/16607812/02c3d431-1bd1-47e5-907b-c89cf4134564)

**Comment by ibjorn** [comment]
Cracked it.

So, in  `spa.ts` I `provide` the props:

```javascript
const lc = singleSpaVue({
    createApp,
    appOptions: {
        render() {
            return h(App)
        }
    } as any,
    handleInstance: (app, props) => {
        registerPlugins(app)
        app.use(router)
        app.provide('appProps', props)
    }
})
```

And in `App.vue` I simply inject them:

```javascript
const props = inject('appProps')

onMounted(() => {
  console.log(props)
})
```

Easy-peasy, 🍋 squeezy.

**Comment by swrzalek** [comment]
Hello, I wrote an article showing an example of Vue3 and Vite. If you are interested here is the link: https://dev.to/swrzalek/building-a-microfrontend-architecture-with-vue-3-vite-single-spa-b6d
