### ISSUE TITLE
Import Map Overrides panel not showing up in the root project

### ISSUE THREAD

**Issue by tudosev** [WJSoftware/vite-plugin-single-spa#73]
The panel showcased here https://www.npmjs.com/package/import-map-overrides and in single-spa, is not possible to open with vite-plugin-single-spa setup. I assume it's not supported, as i also didn't see anything mentioned about it in the blog series.

Project type: [x] Root Config [ ] Micro-frontend/parcel
Project Framework:  [x] React [ ] Svelte [ ] Vue [ ] Preact [ ] Other: <please specify>

## To Reproduce

1. Go to root project
2. `npm run dev`
3. no imo menu shows up (the bottom right menu)

```
import react from '@vitejs/plugin-react'
import vitePluginSingleSpa from 'vite-plugin-single-spa';
import { defineConfig } from 'vite'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [react(), vitePluginSingleSpa({
    type: 'root',
    imo: '3.1.1',
    importMaps: {
      dev: ['src/importMap.dev.json', 'src/importMap.shared.json'],
      build: ['src/ImportMap.json', 'src/importMap.shared.json']
    }
  })],
})

```
## Expected behavior

Import Map Overrides menu/panel should show up, where you can update/override the imports

## Additional context

If this is not supported due to how the plugin rewires the import maps, then it should be stated in the readme - i think it's a big loss and a nice feature of single-spa.

I hope i can resolve this, and the React HMR (opened another issue), so i can continue using this plugin and Vite

**Comment by webJose** [comment]
Hello. It is fully supported and works as intended.  The `imo` setting stands for "import map overrides".  IMO will only be included if there are import maps.  It seems that you have them.  What local storage key are you setting up for the UI to show up?

**Comment by webJose** [comment]
The HMR is out of my hands.  React's HMR is a Vite feature, not a feature of this plug-in.  Its current design makes it incompatible with single-spa, and once more, is not in my hands to fix.
