### ISSUE TITLE
HMR React not working

### ISSUE THREAD

**Issue by tudosev** [WJSoftware/vite-plugin-single-spa#74]
As mentioned in https://webjose.hashnode.dev/vite-plugin-single-spa-vite-projects-made-single-spa-compatible-with-one-plug-in?source=more_series_bottom_blogs, the HMR is not supported in serve mode.

When i hit save, i can see that App.tsx is pulled in, but changes are not reflected. Please note that i am in the root app serve mode, and mife app in serve mode, and i link the mife via src/spa.tsx (and App.tsx is a child of the mife spa.tsx).

Project type: [x] Root Config [x] Micro-frontend/parcel
Project Framework:  [x] React [ ] Svelte [ ] Vue [ ] Preact [ ] Other: <please specify>

```
import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import vitePluginSingleSpa from 'vite-plugin-single-spa';


// https://vitejs.dev/config/
export default defineConfig({
  plugins: [react(), vitePluginSingleSpa(
    {
      type: 'mife',
      serverPort: 4101,
      spaEntryPoints: 'src/spa.tsx'
    }
  )]
})
```

## Expected behavior

HMR should refresh the changes (the way it works with webpack setup that single-spa is using)

## Screenshots

![image](https://github.com/WJSoftware/vite-plugin-single-spa/assets/34243684/ab9e5aa4-a00f-4146-a386-e1e7e8c0778a)

## Additional context

I think this is a big loss, and should be added to the readme, before one can commit to using this plugin.
This is a neat feature particularly in conjunction with import overrides (https://github.com/WJSoftware/vite-plugin-single-spa/issues/73), so you can load your deployed app (from test environment) and connect just the frontend you're working on.

**Comment by tudosev** [comment]
Aditionally, i never got the error that is mentioned in the blog post:
```
Uncaught Error: application 'mifeA' died in status LOADING_SOURCE_CODE: @vitejs/plugin-react can't detect preamble. Something is wrong. See https://github.com/vitejs/vite-plugin-react/pull/11#discussion_r430879201
    at App.tsx:10:5
```

and i didn't have to disable hmr in vite config
```
// **was not needed**
  server: {
    hmr: false
  }
```

also worth mentioning that when i save `spa.tsx` the changes **do** hot reload, it's when i change the inner childdren, they don't hot reload

**Comment by webJose** [comment]
HMR is not a feature of this plug-in.  Open the issue with Vite.

**Comment by janlat** [comment]
FWIW, hot reload can be fixed by injecting the preamble code at the top of the entrypoint
```ts
import reactPlugin from '@vitejs/plugin-react'
import vitePluginSingleSpa from 'vite-plugin-single-spa'

const ENTRY_POINT = 'src/main.tsx'

const config = {
  plugins: [
    reactPlugin(),
    {
      name: 'inject-react-refresh-preamble',
      transform(code, id) {
        if (id.includes(ENTRY_POINT)) {
          return reactPlugin.preambleCode.replace('__BASE__', '/') + code
        }
      },
    },
    vitePluginSingleSpa({
      type: 'mife',
      spaEntryPoints: ENTRY_POINT,
      // ...
    }),
  ],
  // ...
}
```
and using dynamic import to load the root component in that entrypoint, so that the preamble can actually run before any component imports are resolved
```ts
const reactLifecycles = singleSpaReact({
  loadRootComponent: async () => {
    const { Root } = await import('./root')
    return Root
  },
  // ...
})
```

**Comment by Jordan-Eckowitz** [comment]
> FWIW, hot reload can be fixed by injecting the preamble code at the top of the entrypoint
> 
> ```ts
> import reactPlugin from '@vitejs/plugin-react'
> import vitePluginSingleSpa from 'vite-plugin-single-spa'
> 
> const ENTRY_POINT = 'src/main.tsx'
> 
> const config = {
>   plugins: [
>     reactPlugin(),
>     {
>       name: 'inject-react-refresh-preamble',
>       transform(code, id) {
>         if (id.includes(ENTRY_POINT)) {
>           return reactPlugin.preambleCode.replace('__BASE__', '/') + code
>         }
>       },
>     },
>     vitePluginSingleSpa({
>       type: 'mife',
>       spaEntryPoints: ENTRY_POINT,
>       // ...
>     }),
>   ],
>   // ...
> }
> ```
> 
> and using dynamic import to load the root component in that entrypoint, so that the preamble can actually run before any component imports are resolved
> 
> ```ts
> const reactLifecycles = singleSpaReact({
>   loadRootComponent: async () => {
>     const { Root } = await import('./root')
>     return Root
>   },
>   // ...
> })
> ```

@janlat thanks for this! I was tearing my hair out for a solution here.

- Could you please expand on your comment regarding the `loadRootComponent`? I created a simple root/mife example and its working without this code but guessing there could be some sort of race condition where its needed.
- Also, what is the relative import `Root` pointing to? Can it be imported via an import map or does it have to be a relative path?

**Comment by Jordan-Eckowitz** [comment]
> FWIW, hot reload can be fixed by injecting the preamble code at the top of the entrypoint
> 
> ```ts
> import reactPlugin from '@vitejs/plugin-react'
> import vitePluginSingleSpa from 'vite-plugin-single-spa'
> 
> const ENTRY_POINT = 'src/main.tsx'
> 
> const config = {
>   plugins: [
>     reactPlugin(),
>     {
>       name: 'inject-react-refresh-preamble',
>       transform(code, id) {
>         if (id.includes(ENTRY_POINT)) {
>           return reactPlugin.preambleCode.replace('__BASE__', '/') + code
>         }
>       },
>     },
>     vitePluginSingleSpa({
>       type: 'mife',
>       spaEntryPoints: ENTRY_POINT,
>       // ...
>     }),
>   ],
>   // ...
> }
> ```
> 
> and using dynamic import to load the root component in that entrypoint, so that the preamble can actually run before any component imports are resolved
> 
> ```ts
> const reactLifecycles = singleSpaReact({
>   loadRootComponent: async () => {
>     const { Root } = await import('./root')
>     return Root
>   },
>   // ...
> })
> ```

This does the trick, thank you so much! There's just one thing I'll add for anybody else that stumbles upon this. The custom plugin needs to only be applied when running your local server, if you add this plugin during your build it will crash. Use the `command` attribute to exclude it from your builds.

@webJose it took a bit of investigating to get to this information and I see there's been a bunch of questions related to React HMR. It may be useful to add this to the readme. 

```ts
import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import vitePluginSingleSpa from "vite-plugin-single-spa";

const ENTRY_POINT = "src/spa.tsx";
const PORT_NUMBER = 5000

export default defineConfig(({ command }) => ({
  plugins: [
    react(),
    // command === "serve" ensures this plugin is only used during development (excluded from builds)
    command === "serve" && {
      name: "inject-react-refresh-preamble",
      transform(code, id) {
        if (id.includes(ENTRY_POINT)) {
          return react.preambleCode.replace("__BASE__", "/") + code;
        }
      },
    },
    vitePluginSingleSpa({
      type: "mife",
      serverPort: PORT_NUMBER,
      spaEntryPoints: ENTRY_POINT,
    }),
  ],
}));

```

**Comment by webJose** [comment]
Hello, @Jordan-Eckowitz.  Thanks for your input.  I welcome PR's, if you're interested in adding this to the README.  Note that whatever makes it to the README, though needs to work.

There is the fact that the example is written for projects that don't specify a base (the base is hardcoded as `"/"`).  It would have to be re-written to use the base coming from Vite's configuration.

So, all in all, it is not a tiny thing to add to the README.  Perhaps maybe the README should just have quick link to this issue and any other related issues or discussions?  What do you think?

Think about it and make your mind up.  I'll be glad to welcome your PR should you decide to go for it.

**Comment by Jordan-Eckowitz** [comment]
@webJose I've created a boilerplate pnpm monorepo that includes a root config, microfrontend and a utility module with all the wiring setup: https://github.com/Jordan-Eckowitz/single-spa-vite-react-ts.

It applies best-practices I've dug out from this and other issues related to single-spa, vite and react. Things like import maps, HMR, externalizing dependencies, port definition and base urls are all addressed. Wherever possible I've lifted variables as constants to the top of each `vite.config.ts` file to make management easier.

I'm not sure if you have any references to example setups but I thought this was probably the clearest way to share best practices.

**Comment by webJose** [comment]
Hello, @Jordan-Eckowitz.  I reviewed your repository.  I must commend you on the excellent English spelling and grammar, which is something that is being lost these days, in all languages, not just English, and the overall effort you clearly made towards putting the repository together.

I would be OK in adding a link to your repository in this repository's README for React people looking for a comprehensive example.  Along these lines, I'd welcome a PR that adds a section before the Quickstart section named "Repository Examples and Extra Information", where links to other resources can be progressively added.

A couple of notes on what I found in your repository:

+ [This line](https://github.com/Jordan-Eckowitz/single-spa-vite-react-ts/blob/639321eb3849b7ce99d8e0e39d89ca95e8614be9/packages/mife/vite.config.ts#L39) seems to continue to hardcode the base.  Something needs to be done about that.  Being that an in-situ plug-in, it should be possible to automatically pick up the base as opposed to hardcode it/repeat it.
+ On non-root projects (MIFE and utility projects) where `vite-plugin-single-spa` is configured with a port number, there is **no need** to configure `server.port`, `preview.port` or `server.origin`.  All three are set by this plug-in.  Example [here](https://github.com/Jordan-Eckowitz/single-spa-vite-react-ts/blob/639321eb3849b7ce99d8e0e39d89ca95e8614be9/packages/mife/vite.config.ts#L28).

**Comment by Jordan-Eckowitz** [comment]
> Hello, @Jordan-Eckowitz. I reviewed your repository. I must commend you on the excellent English spelling and grammar, which is something that is being lost these days, in all languages, not just English, and the overall effort you clearly made towards putting the repository together.
> 
> I would be OK in adding a link to your repository in this repository's README for React people looking for a comprehensive example. Along these lines, I'd welcome a PR that adds a section before the Quickstart section named "Repository Examples and Extra Information", where links to other resources can be progressively added.
> 
> A couple of notes on what I found in your repository:
> 
> * [This line](https://github.com/Jordan-Eckowitz/single-spa-vite-react-ts/blob/639321eb3849b7ce99d8e0e39d89ca95e8614be9/packages/mife/vite.config.ts#L39) seems to continue to hardcode the base.  Something needs to be done about that.  Being that an in-situ plug-in, it should be possible to automatically pick up the base as opposed to hardcode it/repeat it.
> * On non-root projects (MIFE and utility projects) where `vite-plugin-single-spa` is configured with a port number, there is **no need** to configure `server.port`, `preview.port` or `server.origin`.  All three are set by this plug-in.  Example [here](https://github.com/Jordan-Eckowitz/single-spa-vite-react-ts/blob/639321eb3849b7ce99d8e0e39d89ca95e8614be9/packages/mife/vite.config.ts#L28).

Thanks for the constructive feedback, really appreciate it! 

- Regarding your first point I lifted out the plugin into `viteSingleSpaFastRefreshPlugin` as shown below. The base is determined using the `configResolved` hook instead of manually being written in - is this along the lines of what you were thinking? If so, I can package this up and push to npm.
- Regarding the second point thanks for catching this - I removed references to server and preview ports in the `mife` and `util` packages.

```ts
import { defineConfig, Plugin } from "vite";
import react from "@vitejs/plugin-react";
import vitePluginSingleSpa from "vite-plugin-single-spa";
import externalize from "vite-plugin-externalize-dependencies";

const viteSingleSpaFastRefreshPlugin = (): Plugin => {
  let base = "";
  return {
    // this ensures that React Fast Refresh (HMR) is properly setup in the development environment.
    // https://github.com/WJSoftware/vite-plugin-single-spa/issues/74#issuecomment-2315823945
    name: "inject-react-refresh-preamble",
    configResolved(resolvedConfig) {
      base = resolvedConfig.base;
    },
    transform(code, id) {
      if (id.includes(ENTRY_POINT)) {
        return react.preambleCode.replace("__BASE__", base) + code;
      }
    },
  };
};

/** single-spa entry point which contains references to lifecycles and shared exports */
const ENTRY_POINT = "src/spa.tsx";

/** Port for running local server and build previews */
const PORT = 5001;

/** These are other single-spa applications, that are imported inside this application, as dependencies.
 * These externals are made available within this application via the root config import map.
 * For more details on why this is required see here: https://github.com/WJSoftware/vite-plugin-single-spa/discussions/160  */
const APPLICATION_EXTERNALS: string[] = ["@demo/util"];

/** These are NPM packages, which are imported via the root config import map, in the built environment */
const NPM_EXTERNALS: string[] = ["react", "react-dom"];

// TODO: replace this with the actual CDN URL
const BASE_URL_DEPLOYMENT = `http://localhost:${PORT}/`;

// https://vitejs.dev/config/
export default defineConfig(({ command }) => ({
  // the base url is injected into any assets to ensure they're http references in production (not relative paths)
  base: command === "serve" ? "/" : BASE_URL_DEPLOYMENT,
  plugins: [
    react(),
    // command === "serve" ensures this plugin is only used during development (excluded from builds)
    command === "serve" && viteSingleSpaFastRefreshPlugin(),
    vitePluginSingleSpa({
      type: "mife",
      serverPort: PORT,
      spaEntryPoints: ENTRY_POINT,
    }),
    externalize({ externals: APPLICATION_EXTERNALS }),
  ],
  build: {
    rollupOptions: { external: [...APPLICATION_EXTERNALS, ...NPM_EXTERNALS] },
  },
}));

```

**Comment by webJose** [comment]
Yes, using `resolvedConfig` is the way to go.

Here are some pointers I believe you should take into account if you want to package the plug-in in its own NPM package:

+ Make sure you unit test.  This package, for instance, has 120 unit tests and they only cover the plug-in.  CSS injection doesn't currently have unit testing.
+ This package allows  multiple entry points.  Your code currently assumes that there will only be one entry point.  Furthermore, the code is written to use the constant ENTRY_POINT, but if packaged in an NPM package, it must obtain the entry points from the rollup node in `resolvedConfig`.
+ Vite encourages a plug-in naming convention.  Follow it.

I guess this is what comes to mind.  Good luck with your endeavor.

**Comment by 0-don** [comment]
@webJose 

What do you think about this react example, seems to be working perfectly deployed or in dev, with all the latest versions

https://github.com/0-don/single-spa-vite

I got inspired by [Jordan-Eckowitz](https://github.com/Jordan-Eckowitz)

**Comment by webJose** [comment]
> [@webJose](https://github.com/webJose)
> 
> What do you think about this react example, seems to be working perfectly deployed or in dev, with all the latest versions
> 
> https://github.com/0-don/single-spa-vite
> 
> I got inspired by [Jordan-Eckowitz](https://github.com/Jordan-Eckowitz)

If it works for you, great!
