### ISSUE TITLE
Single-spa types not exported with plugin

### ISSUE THREAD

**Issue by amalvivek** [WJSoftware/vite-plugin-single-spa#80]
I am seeing the following issue when I integrate the plugin to my root app. I am not certain however I think this [github issue](https://github.com/single-spa/single-spa/issues/1115) on single-spa could be related to the problem I am seeing.

<img width="442" alt="image" src="https://github.com/WJSoftware/vite-plugin-single-spa/assets/43559204/94daa60a-a99f-4bed-93c4-0d622e070e51">

`Vue: Could not find a declaration file for module single-spa.
./node_modules/single-spa/lib/es2015/esm/single-spa.min.js
implicitly has an any type.
There are types at
./node_modules/single-spa/typings/single-spa.d.ts
, but this result could not be resolved when respecting package.json exports. The single-spa library may need to update its package.json or typings.`

Project type: [x ] Root Config [ ] Micro-frontend/parcel
Project Framework:  [ ] React [ ] Svelte [ x] Vue [ ] Preact [ ] Other: <please specify>

My vite config:

```
import { fileURLToPath, URL } from 'node:url'
import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'
import vitePluginSingleSpa from 'vite-plugin-single-spa';

export default defineConfig({
  plugins: [vue(), vitePluginSingleSpa({
    type: 'root',
    imo: '3.1.1'
  })],
  resolve: {
    alias: {
      '@': fileURLToPath(new URL('./src', import.meta.url))
    }
  }
})
```

**Comment by webJose** [comment]
Hello, @amalvivek.  Those are functions that are provided within the `single-spa` NPM package, not this package.  This package doesn't ship `single-spa` and merely has it as a peer dependency.

**Comment by amalvivek** [comment]
Ah apologies!

**Comment by webJose** [comment]
No problem.  FYI, `single-spa` v7 will be out with better typing.  For now, you'll have to deal with the current types `single-spa` provides.  If you get in trouble like this, you could use TS tricks like the `@ts-expect-error` comment.
