### ISSUE TITLE
Dynamically download microfrontends apps and write import map overrides

### ISSUE THREAD

**Issue by satyam-veris** [WJSoftware/vite-plugin-single-spa#84]
Hello,

I'm currently using your plugin for my project and I've encountered a specific use case that I need help with.

In my project, the details of my microfrontends are served by an API. This API delivers an array of objects, where each object contains a bundle URL, app name, active routes, and some other metadata. Due to the dynamic nature of my project, I'm unable to write a static import map file and hardcode the app URLs in it.

What I'm looking for is a way to write the import map once the API has delivered all the app metadata. Only then do I want to write the import maps and register the application using single-spa.

I have already tried a couple of solutions but unfortunately, none of them worked. I tried embedding scripts after the API calls successfully returned the data, but I got a "mifeA died loading source code" error. I also tried installing `import-map-override` and adding overrides after the API call was successful, but this didn't work either.

Is there a recommended way to handle this scenario using your plugin? Any guidance or suggestions would be greatly appreciated.

Thank you for your time and assistance.

Sharing code snippet for reference.

`vite.config.js`
```
import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import vitePluginSingleSpa from "vite-plugin-single-spa";

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    react(),
    vitePluginSingleSpa({
      type: "root",
      imo: "2.4.2",
    }),
  ],
});

```

`main.jsx'
```
import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './App';

const mifeBModule = "@learnSspa/mifeB";
 registerApplication({
     name: 'mifeB',
     app: () => import(/* @vite-ignore */ mifeBModule),
     activeWhen: "/"
})
start();

ReactDOM.createRoot(document.getElementById('apps')).render(
    <React.StrictMode>
        <App />
    </React.StrictMode>
);
```

Best,

**Comment by satyam-veris** [comment]
Thanks for your answer. It was really helpful.

**Comment by crazko** [comment]
Thanks @webJose , the description of the `ETag` was helpful for me as well. Didn't know about this.

(I was also looking for how to add hash to the exported entry point file name, so I stumbled here.)
