### ISSUE TITLE
CSS of MIFE not getting imported in root app

### ISSUE THREAD

**Issue by imsatyam2111** [WJSoftware/vite-plugin-single-spa#87]
## Describe the bug
I am migrating my CRA + Craco microfrontend app to vite using vite-plugin-single-spa. I have converted the root app as well in vite using the same plugin.

The problem I am facing is css is not being imported when loading my microfrontend into the root app with default built settings.

Project type: [ ] Root Config [✅ ] Micro-frontend/parcel
Project Framework:  [ ✅] React [ ] Svelte [ ] Vue [ ] Preact [ ] Other: <please specify>

## To Reproduce

Also include Vite's configuration (the contents of `vite.config.js/ts`).

```
import { defineConfig, loadEnv } from "vite";
import react from "@vitejs/plugin-react";
import vitePluginSingleSpa from "vite-plugin-single-spa";
import tsconfigPaths from "vite-tsconfig-paths";

export default ({ mode }) => {
  // load app-level env vars to node-level env vars.
  process.env = { ...process.env, ...loadEnv(mode, process.cwd() )};

  return defineConfig({
    plugins: [
      react(),
      tsconfigPaths(),
      vitePluginSingleSpa({
        type: "mife",
        serverPort: 4101,
        spaEntryPoints: "src/app-login.jsx",
      }),
    ],
    base: process.env.VITE_BASE_URL,
    // build: {
    //   rollupOptions: {
    //     output: {
    //       manualChunks: undefined,
    //       inlineDynamicImports: true,
    //     }
    //   }
    // }
  });
}
```

`app-login.jsx`

```
import React from 'react';
import ReactDOMClient from 'react-dom/client';
import singleSpaReact from 'single-spa-react';
import { cssLifecycleFactory } from 'vite-plugin-single-spa/ex';

import App from './App'

const lc = singleSpaReact({
    React,
    ReactDOMClient,
    rootComponent: App,
    errorBoundary() {
        return <div>Error</div>
    }
});

const cssLc = cssLifecycleFactory('app-login');
export const bootstrap = [cssLc.bootstrap, lc.bootstrap];
export const mount = [cssLc.mount, lc.mount];
export const unmount = [cssLc.unmount, lc.unmount];
```

## Expected behavior

CSS should get imported when integrated in root App

## Screenshots
dist folder with default build settings
![image](https://github.com/WJSoftware/vite-plugin-single-spa/assets/52671059/71e49ce0-89d2-4674-9306-ef0f249aad20)

browser console
JS got fetched
![image](https://github.com/WJSoftware/vite-plugin-single-spa/assets/52671059/3c03e087-32d8-4e45-9b30-e0f8420da2ea)

No css for MIFE
![image](https://github.com/WJSoftware/vite-plugin-single-spa/assets/52671059/7e7e1ac6-bde9-4cd5-b891-4dd840aa0fc8)

## Browser list:

| Browser Name | Browser Version | Platform |
| - | - | - |
| Acme Browser (example row) | v1.0.0 | Windows x64 |

## Additional context

Root app `vite.config.js`
```
import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import vitePluginSingleSpa from "vite-plugin-single-spa";

export default defineConfig({
  plugins: [
    react(),
    vitePluginSingleSpa({
      type: "root",
      imo: "2.4.2",
    }),
  ],
});

```

The interesting thing is when I am adding following piece in the MIFE vite.config.js file, css does get imported in the root app. The difference I see is the default build settings divide the js and css files in chunks, whereas the following build configs, builds the app in a single js file and a single css file.

```
build: {
   rollupOptions: {
     output: {
          manualChunks: undefined,
          inlineDynamicImports: true,
     }
  }
}
```
dist folder screenshot
![image](https://github.com/WJSoftware/vite-plugin-single-spa/assets/52671059/8f3014ed-6b2c-48d4-8287-bbe51914d046)

Browser console:
CSS does get imported
![image](https://github.com/WJSoftware/vite-plugin-single-spa/assets/52671059/6f56fb63-5dcc-4bc7-83f2-fad509685164)

**Comment by webJose** [comment]
Hello, @imsatyam2111.  The plug-in's algorithm to determine the CSS files to mount relies on Vite's output.  If the entry point JS file contains no CSS files listed,  then the map is empty and mounting the MFE triggers no CSS uploads.  This is what is most likely happening in your case.  This means that all CSS is tied to JS chunks that are dynamically imported.

Vite is the one that imports CSS dynamically imported.  This plug-in only controls their `disabled` HTML attribute when mounting or unmounting.  I would say this particular problem seems to be related to Vite, not this plug-in.

If you trigger the dynamic imports, do you see any more CSS files being fetched?

**Comment by webJose** [comment]
From [Vite's documentation](https://vitejs.dev/guide/features.html#css-code-splitting):

> ## CSS Code Splitting
> Vite automatically extracts the CSS used by modules in an async chunk and generates a separate file for it. The CSS file is automatically loaded via a <link> tag when the associated async chunk is loaded, and the async chunk is guaranteed to only be evaluated after the CSS is loaded to avoid [FOUC](https://en.wikipedia.org/wiki/Flash_of_unstyled_content#:~:text=A%20flash%20of%20unstyled%20content,before%20all%20information%20is%20retrieved.).

> 
> If you'd rather have all the CSS extracted into a single file, you can disable CSS code splitting by setting [build.cssCodeSplit](https://vitejs.dev/config/build-options.html#build-csscodesplit) to false.

You could test `build.cssCodeSplit` if you like, but as you can see, dynamic imports, by default, split CSS and the corresponding JS files are in charge of mounting the CSS.

**Comment by webJose** [comment]
I also see a Vite v5 note in [this piece](https://vitejs.dev/guide/features.html#disabling-css-injection-into-the-page) (are you using Vite v5?):

> Default and named imports from CSS files (e.g `import style from './foo.css'`) are removed since Vite 5. Use the `?inline` query instead.

I am unsure if this applies to you.  Something to have in mind if you are doing named or default imports of CSS.

**Comment by imsatyam2111** [comment]
> Hello, @imsatyam2111. The plug-in's algorithm to determine the CSS files to mount relies on Vite's output. If the entry point JS file contains no CSS files listed, then the map is empty and mounting the MFE triggers no CSS uploads. This is what is most likely happening in your case. This means that all CSS is tied to JS chunks that are dynamically imported.
> 
> Vite is the one that imports CSS dynamically imported. This plug-in only controls their `disabled` HTML attribute when mounting or unmounting. I would say this particular problem seems to be related to Vite, not this plug-in.
> 
> If you trigger the dynamic imports, do you see any more CSS files being fetched?

Most of CSS in my are coming up from my internal style guide and module level css. Module level css are being imported like `import stylse from './style.module.css'`. And also I have many components from antd.

**Comment by webJose** [comment]
> Most of CSS in my are coming up from my internal style guide and module level css. Module level css are being imported like import stylse from './style.module.css'. And also I have many components from antd.

Ok, this is no longer supported in Vite v5.  If you are using Vite v5, that's it.  Move to Vite v4 or stop doing default imports.

**Comment by webJose** [comment]
Closing the issue due to inactivity.  Feel free to reopen if needed.  Thanks!

**Comment by webJose** [comment]
Hello, @PabloFX.  Currently working, but quickly:  Importing CSS in `spa.ts` looks weird to me.  Are we talking parcels or are we talking MFE's?

Version of the plug-in?
Version of Vite?

**Comment by PabloFX** [comment]
Hi, 
```
"vite": "^5.2.8",
"vite-plugin-single-spa": "^0.7.0",
```

**Comment by webJose** [comment]
I can't help if you only reply some of the questions.  Please complete the information.

**Comment by PabloFX** [comment]
Sorry I missed the first question. The root app will handle different mife apps served on separate pages. So this is MFE app that uses dynamic imports for routes

**Comment by PabloFX** [comment]
if this would help -  the assets are bundled (at least seems to be) correctly with proper CSS code inside:
<img width="258" alt="image" src="https://github.com/WJSoftware/vite-plugin-single-spa/assets/46690088/a8551c23-7958-43eb-99fe-7504b5a6a797">

The issue I see is that it's not appended in dist spa.js file:
<img width="192" alt="image" src="https://github.com/WJSoftware/vite-plugin-single-spa/assets/46690088/75f7991e-aad8-4822-b770-394a6d6cc812">

**Comment by webJose** [comment]
Move the importing of the CSS file out of `spa.ts` and into the entry point component.  Then rebuild.

**Comment by PabloFX** [comment]
it seems to be working, thank you!

**Comment by valeriiavask** [comment]
Jose, using the plugin in production for quite some time, with no issues! thanks for building it!

As our app grew bigger, vite did auto code splitting, and we noticed that the CSS file is not included in the mfe JS - it happens randomly - sometimes we have to trigger another build/deploy so that the CSS is included (to be loaded/bootstrapped)

it's like there's a race condition somewhere - i will look into it more and report back but for now i will try the things mentioned in this thread.

also if you have more tips, or things to check maybe in the plugin level, please let me know

**Comment by quentin-desbin** [comment]
> Jose, using the plugin in production for quite some time, with no issues! thanks for building it!
> 
> As our app grew bigger, vite did auto code splitting, and we noticed that the CSS file is not included in the mfe JS - it happens randomly - sometimes we have to trigger another build/deploy so that the CSS is included (to be loaded/bootstrapped)
> 
> it's like there's a race condition somewhere - i will look into it more and report back but for now i will try the things mentioned in this thread.
> 
> also if you have more tips, or things to check maybe in the plugin level, please let me know

Hi ! I'm reopening this because we have exactly the same thing

Did you finally find any solution / workarround / tips ?

Thanks

**Comment by valeriiavask** [comment]
@quentin-desbin yes, the solution was to move the css imports out of the spa.ts file
so in spa.ts you provide a rootComponent for example <App/>, and you import all the css inside <App/>

> Move the importing of the CSS file out of `spa.ts` and into the entry point component. Then rebuild.

**Comment by mateusduraes** [comment]
> > [@quentin-desbin](https://github.com/quentin-desbin) yes, the solution was to move the css imports out of the spa.ts file
> > so in spa.ts you provide a rootComponent for example `<App/>`, and you import all the css inside `<App/>`
> > > Move the importing of the CSS file out of `spa.ts` and into the entry point component. Then rebuild.
> 
> It's already my case, my css is imported on App only nothing on spa file directly.

Did you find how to fix the issue?
I have pretty much teh same problem.
I have a `root.css` file imported in the `root.component.tsx` file.
`root.component.tsx` is the main componetn which I'm importing in `spa.ts`



```typescript
// spa.ts
import React from 'react';

import ReactDOMClient from 'react-dom/client';
import singleSpaReact from 'single-spa-react';
import { cssLifecycleFactory } from 'vite-plugin-single-spa/ex';

import { Root } from './root.component';

const lifecycles = singleSpaReact({
  React,
  ReactDOMClient,
  rootComponent: Root,
  errorBoundary(err) {
    // Customize the root error boundary for your microfrontend here.
    return React.createElement('div', null, 'An error occurred', err.message);
  },
});

const cssLc = cssLifecycleFactory('spa' /* optional factory options */);
export const bootstrap = [cssLc.bootstrap, lifecycles.bootstrap];
export const mount = [cssLc.mount, lifecycles.mount];
export const unmount = [cssLc.unmount, lifecycles.unmount];

```


```typescript
// root.component.tsx
// ommited imports
import './root.css';

export function Root() {
  // ommited application code...
}
```


Sometimes the spa css file is included in the build, sometimes it's not.
Exactly like people described above.

**Comment by webJose** [comment]
Guys, hello.  This doesn't seem to be about this plug-in.  This seems to be about Vite.  Have you guys raised the issue with them?  This plug-in only collects bundle data generated elsewhere.  In other words, this plug-in *passively* reviews data and only at the end of the bundling process does it write the collected data.  This sounds like a problem with the upstream because the array is empty.  This means that this plug-in did not find (in the instances that fails) any CSS bundle data.

**Comment by mateusduraes** [comment]
> Guys, hello. This doesn't seem to be about this plug-in. This seems to be about Vite. Have you guys raised the issue with them? This plug-in only collects bundle data generated elsewhere. In other words, this plug-in _passively_ reviews data and only at the end of the bundling process does it write the collected data. This sounds like a problem with the upstream because the array is empty. This means that this plug-in did not find (in the instances that fails) any CSS bundle data.

Could you please point me to some file or a quick way to debug this build?
That would be helpful, thank you.


And, do you see anything wrong with how I'm importing the css file? (based on the recommendation of the plugin)

**Comment by webJose** [comment]
> Could you please point me to some file or a quick way to debug this build? That would be helpful, thank you.
> 
> And, do you see anything wrong with how I'm importing the css file? (based on the recommendation of the plugin)

The plug-in can log to a file (because it is too much data for console logging) the bundle data.  You can start there.  I haven't done it myself for so long because this plug-in has been working nicely for the majority of its lifetime.  Let me see how that's done...

BTW, I don't see an issue about how you import the CSS.  That looks OK to me.

**Comment by mateusduraes** [comment]
> > Guys, hello. This doesn't seem to be about this plug-in. This seems to be about Vite. Have you guys raised the issue with them? This plug-in only collects bundle data generated elsewhere. In other words, this plug-in _passively_ reviews data and only at the end of the bundling process does it write the collected data. This sounds like a problem with the upstream because the array is empty. This means that this plug-in did not find (in the instances that fails) any CSS bundle data.
> 
> Not yet, but what I didn't understand is that the bundled files are correctly created, the log shows the good files, maybe you can indicates which output is used by the plugin to better fill the issue on vite and indicates where the problem seems to be present.
> 
> > > > [@quentin-desbin](https://github.com/quentin-desbin) yes, the solution was to move the css imports out of the spa.ts file
> > > > so in spa.ts you provide a rootComponent for example `<App/>`, and you import all the css inside `<App/>`
> > > > > Move the importing of the CSS file out of `spa.ts` and into the entry point component. Then rebuild.
> > > 
> > > 
> > > It's already my case, my css is imported on App only nothing on spa file directly.
> > 
> > 
> > Did you find how to fix the issue? I have pretty much teh same problem. I have a `root.css` file imported in the `root.component.tsx` file. `root.component.tsx` is the main componetn which I'm importing in `spa.ts`
> 
> No real solution for now, we are using an after_script in CI to detect if the array is empty and updating the bundled js file with the correct css name if it's missed. It's an "hot patch" but it ensures that 100% of my builds works now.

Hey Quentin, do you mind sharing a bit on how you solved it using this after_script?
I'll be running some builds today and trying to find the issue as well

**Comment by webJose** [comment]
Ok, [this type](https://github.com/WJSoftware/vite-plugin-single-spa/blob/716399a8713d1f1d6ef0966891beedd0c3bb2149/src/vite-plugin-single-spa.d.ts#L21) describes the logging options for the plug-in.

So, if I'm reading this correctly, you do:

```ts
vitePluginSingleSpa({
  ...,
  logging: {
    chunks: true,
  }
});
```

It will then write to the file vpss.log the bundle information.

**Comment by quentin-desbin** [comment]
> Hey Quentin, do you mind sharing a bit on how you solved it using this after_script?
> I'll be running some builds today and trying to find the issue as well

Yes, that's what we done for our gitlab ci build s

```yaml
.after-patch-build: &after-patch-build
  |
  CSS_URI=$(ls -1 dist/assets/vpss*main-*.css 2>/dev/null)
  MAIN_JS=$(ls -1 dist/assets/main-*.js 2>/dev/null)
  TXT_RED="\e[31m" && TXT_CLEAR="\e[0m" && TXT_GREEN="\e[32m"
  if grep -q '{\\"main\\":\[\]}' $MAIN_JS; then
      echo -e "${TXT_RED}🚨 Missing CSS in SPA main.js${TXT_CLEAR}"
      if [ -n "$CSS_URI" ]; then
          CSS_URI=${CSS_URI#dist/}
          ESCAPED_CSS_URI=$(echo "$CSS_URI" | sed 's/\//\\\//g')
          sed -i -r 's/"\{\\\"main\\\":\[\]\}"/"{\\\"main\\\":[\\\"'"${ESCAPED_CSS_URI}"'\\\"]}"/g' $MAIN_JS
          if grep -q '{\\"main\\":\[\]}' $MAIN_JS; then
          echo -e "${TXT_RED}🚨 Still missing CSS${TXT_CLEAR}"
          exit 1
          else
              echo -e "${TXT_GREEN}✅ main.js patched successfully${TXT_CLEAR}"
          fi
      fi
  else
      echo -e "${TXT_GREEN}✅ mains.js is good, no need to patch it${TXT_CLEAR}"
  fi

#usage in job
build:
    script: npm run build
    after_script:
      - *after-patch-build
```

**Comment by webJose** [comment]
[This line](https://github.com/WJSoftware/vite-plugin-single-spa/blob/716399a8713d1f1d6ef0966891beedd0c3bb2149/src/plugin-factory.ts#L334) is the start of the chunk logic.

Apologies for this comment [here](https://github.com/WJSoftware/vite-plugin-single-spa/blob/716399a8713d1f1d6ef0966891beedd0c3bb2149/src/plugin-factory.ts#L338).  What in the world?  LOL.  I had a grammar hiccup.  I guess I meant to say that the solution was to first build the entire log entry, and then write it in one Go.

**Comment by dc-riskhub** [comment]
HI @webJose, thanks for your work. I submitted a PR that attempts to fix this problem, at least for Vite 7. Thanks
